parameters:
    adherent_interests:
        agriculture: Agriculture
        social: Affaires sociales
        culture: Culture
        economie: Économie
        education: Éducation
        egalite: Egalité F / H
        emploi: Emploi
        environement: Environnement
        europe: Europe
        international: International
        jeunesse: Jeunesse
        justice: Justice
        numerique: Numérique
        sante: Santé
        securite: Sécurité
        sport: Sport
        territoire: Territoire
        institution: Vie publique & institutions

    mailchimp_interests:
        agriculture: 1
        social: 2
        culture: 3
        economie: 4
        education: 5
        egalite: 6
        emploi: 7
        environement: 8
        europe: 9
        international: 10
        jeunesse: 11
        justice: 12
        numerique: 13
        sante: 14
        securite: 15
        sport: 16
        territoire: 17
        institution: 18
